version: '3.7'

services:
  bot:
    build: bot
    restart: always
    environment:
      - TELEGRAM_TOKEN
      - DOMAIN
      - ENVIRONMENT
    ports:
      - 3001:3001
    volumes:
      - ${PWD}/bot:/bot
